export const projectsData = [
  {
    id: "thin-film-research",
    name: "FeCo/CoFe Thin Film Fabrication",
    description: "DC magnetron sputtering of ferromagnetic alloy thin films on flexible polymer substrates. XRD, VSM, FMR characterization.",
    date: "2024-03-15",
    category: "semiconductor",
    tags: ["Sputtering", "XRD", "VSM", "FMR", "Thin Films"],
    link: "/research",
  },
  {
    id: "esp32-cam-microscope",
    name: "ESP32-CAM Digital Microscope",
    description: "Low-cost wireless digital microscope with real-time streaming, adjustable resolution, and exposure control via WebSocket interface.",
    date: "2023-11-20",
    category: "embedded",
    tags: ["ESP32", "Embedded C", "WebSockets", "Wireless"],
    link: "/embedded",
  },
  {
    id: "arduino-line-follower",
    name: "PID Line Follower Robot",
    description: "Autonomous robot using 5-channel IR array with PID control. Weighted position estimation, Ziegler-Nichols tuning, 0.8 m/s max speed.",
    date: "2023-09-10",
    category: "embedded",
    tags: ["Arduino", "PID", "Embedded", "Robotics"],
    link: "/embedded",
  },
  {
    id: "vlsi-digital-design",
    name: "RTL Digital Logic Core Development",
    description: "Parameterized ALU, Mealy/Moore FSMs, UART transmitter designed in Verilog. Functional verification with self-checking testbenches.",
    date: "2023-07-30",
    category: "digital",
    tags: ["Verilog", "Vivado", "ModelSim", "FPGA"],
    link: "/projects",
  },
  {
    id: "embedded-prototyping",
    name: "Embedded Systems Prototyping",
    description: "Microcontroller-based sensor integration and actuator control across ESP32, Arduino, and 8051 platforms.",
    date: "2023-05-12",
    category: "embedded",
    tags: ["ESP32", "Arduino", "8051", "Sensors"],
    link: "/embedded",
  },
  {
    id: "semiconductor-simulation",
    name: "Semiconductor Device Simulation",
    description: "MATLAB-based modeling of semiconductor device characteristics including carrier transport, junction behavior, and material properties.",
    date: "2023-02-01",
    category: "semiconductor",
    tags: ["MATLAB", "Modeling", "Simulation"],
    link: "/research",
  },
  {
    id: "sensor-interface",
    name: "Multisensor Data Acquisition",
    description: "8051-based multi-sensor interface for environmental monitoring. I2C sensor communication, UART data logging.",
    date: "2023-01-15",
    category: "embedded",
    tags: ["8051", "I2C", "UART", "Embedded C"],
    link: "/embedded",
  },
  {
    id: "pcb-design",
    name: "Custom Sensor Node PCB",
    description: "2-layer PCB design for ESP32-based environmental sensor node. Schematic capture and layout in Proteus.",
    date: "2022-11-20",
    category: "embedded",
    tags: ["PCB Design", "Proteus", "ESP32", "KiCad"],
    link: "/embedded",
  },
];
