export const projectsData = [
  {
    id: 1,
    name: "Thin Film & Spintronics Research",
    description: "FeCo/CoFe thin film fabrication on flexible substrates via DC magnetron sputtering",
    date: "2024-03-15",
    href: "/research",
    external: false,
  },
  {
    id: 2,
    name: "ESP32-CAM Digital Microscope",
    description: "Low-cost wireless microscope for material inspection with real-time streaming",
    date: "2023-11-20",
    href: "/embedded",
    external: false,
  },
  {
    id: 3,
    name: "Arduino Line Follower Robot",
    description: "PID-controlled autonomous navigation using IR sensor array",
    date: "2023-09-10",
    href: "/embedded",
    external: false,
  },
  {
    id: 4,
    name: "VLSI Digital Logic Core Design",
    description: "RTL development of ALU, FSM, and UART in Verilog with verification",
    date: "2023-07-30",
    href: "/projects",
    external: false,
  },
  {
    id: 5,
    name: "Embedded Systems Prototyping",
    description: "Multisensor data acquisition with 8051 and ESP32 platforms",
    date: "2023-05-12",
    href: "/embedded",
    external: false,
  },
  {
    id: 6,
    name: "Semiconductor Device Simulation",
    description: "MATLAB-based modeling of semiconductor device characteristics",
    date: "2023-02-01",
    href: "/research",
    external: false,
  },
];

